site_name: Fab Foundation Poland
repo_name: judycurie/ffp
site_url: https://www.fabfoundation.pl/
copyright: Fab Foundation Poland

nav:
    - Home: index.md
    - About:
      - nav/about/mission.md
      - nav/about/founders.md
      - nav/about/statut.md
      - nav/about/regulations.md

    - Research:
      - nav/research/areas.md
      - nav/research/international-scientific-council.md
      - nav/resources.md
    - FabLabs:
      -  nav/fablabs/fablab-model.md
      -  nav/fablabs/fab-institute.md
    - Events: nav/events.md

    - Donate:
      - nav/donate/donate.md
      - nav/donate/tax-deductions.md
    - Contact: nav/contact.md

theme:
  name: simple-blog
  custom_dir: template
  title_style: normal
  favicon: assets/ffp-logo-white.svg
  logo: assets/ffp-icon.jpg
  # theme_style: light
  colors:
    text: black
    title: black
    primary: black
    background: white
plugins:
    - mkdocs-video
